name:                nbe-edsl
version:             0.1.0.0
github:              "nachivpn/nbe-edsl"
license:             BSD3
author:              "Nachiappan Valliappan"
maintainer:          "nacval@chalmers.se"
copyright:           "2021 Nachiappan Valliappan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nachivpn/nbe-edsl#readme>

dependencies:
    - base >= 4.7 && < 5
    - constraints
    - pretty >= 1.1.3.6
    - mtl >= 2.2.2
    - array >= 0.5

library:
  source-dirs: src